"""Base policy interfaces for pluggable defender generation."""

from __future__ import annotations

from dataclasses import dataclass, field
from typing import Any


@dataclass
class CodeCandidate:
    """Single candidate solution generated by a policy."""

    code: str
    source: str
    metadata: dict[str, Any] = field(default_factory=dict)


class CoderPolicy:
    """Policy interface used by trainer and app."""

    name = "base"

    def generate_candidates(self, state: dict[str, Any], num_candidates: int) -> list[CodeCandidate]:
        raise NotImplementedError
